# Generated by Django 6.0.1 on 2026-04-03 13:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('creator_name', models.CharField(max_length=150)),
                ('category', models.CharField(choices=[('smartphones', 'Smartphones'), ('pc_hardware', 'PC Hardware'), ('programming', 'Programming'), ('ai', 'AI / Machine Learning'), ('cybersecurity', 'Cybersecurity'), ('gaming_tech', 'Gaming Tech'), ('consumer_tech', 'Consumer Tech'), ('tech_news', 'Tech News')], max_length=50)),
                ('description', models.TextField()),
                ('subscribers', models.PositiveIntegerField()),
                ('youtube_url', models.URLField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='channel_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
